server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/registration
    username:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

file:
  upload-dir: /uploads

gcp:
  config:
    file: bug-tracker-391811-a5f036ef7811.json
  project:
    id: bug-tracker-391811
  bucket:
    id: adfsga
  dir:
    name: dev

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 30000000
